// <auto-generated />
using System;
using FinancasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004041802_AdicionaCartoes")]
    partial class AdicionaCartoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FinancasApi.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("FinancasApi.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#8A05BE",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Nubank"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#EC0000",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Santander"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#CC092F",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Bradesco"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#EC7000",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Itaú"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#FCDD00",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Banco do Brasil"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#005CA9",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Caixa"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#0A2F5C",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Safra"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#FF7A00",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Inter"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#242424",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "C6 Bank"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#001E62",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "BTG Pactual"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#21C25E",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "PicPay"
                        },
                        new
                        {
                            Id = 12,
                            Color = "#009EE3",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Mercado Pago"
                        },
                        new
                        {
                            Id = 13,
                            Color = "#00C2CB",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Neon"
                        },
                        new
                        {
                            Id = 14,
                            Color = "#00D95F",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Next"
                        },
                        new
                        {
                            Id = 15,
                            Color = "#3FA110",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Sicredi"
                        },
                        new
                        {
                            Id = 16,
                            Color = "#003641",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Sicoob"
                        },
                        new
                        {
                            Id = 17,
                            Color = "#004A9F",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Banrisul"
                        },
                        new
                        {
                            Id = 18,
                            Color = "#1CA53B",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Banco Original"
                        },
                        new
                        {
                            Id = 19,
                            Color = "#94A3B8",
                            Icon = "🏦",
                            IsSystem = true,
                            Name = "Outro"
                        });
                });

            modelBuilder.Entity("FinancasApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#60a5fa",
                            Icon = "🏠",
                            IsSystem = true,
                            Name = "Moradia"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#34d399",
                            Icon = "🛒",
                            IsSystem = true,
                            Name = "Alimentação"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#f87171",
                            Icon = "🍕",
                            IsSystem = true,
                            Name = "Delivery"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#fbbf24",
                            Icon = "🎉",
                            IsSystem = true,
                            Name = "Final de Semana"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#a78bfa",
                            Icon = "🚗",
                            IsSystem = true,
                            Name = "Transporte"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#f472b6",
                            Icon = "💊",
                            IsSystem = true,
                            Name = "Saúde"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#818cf8",
                            Icon = "📱",
                            IsSystem = true,
                            Name = "Assinaturas"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#fb923c",
                            Icon = "👕",
                            IsSystem = true,
                            Name = "Roupas"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#2dd4bf",
                            Icon = "🎮",
                            IsSystem = true,
                            Name = "Lazer"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#e879f9",
                            Icon = "📚",
                            IsSystem = true,
                            Name = "Educação"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#facc15",
                            Icon = "💡",
                            IsSystem = true,
                            Name = "Contas Fixas"
                        },
                        new
                        {
                            Id = 12,
                            Color = "#94a3b8",
                            Icon = "🛠️",
                            IsSystem = true,
                            Name = "Outros"
                        });
                });

            modelBuilder.Entity("FinancasApi.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ClosingDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DueDay")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Last4")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<decimal>("Limit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("FinancasApi.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("InstallmentGroupId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("InstallmentTotal")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceMonth")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("CreditCardId", "InvoiceYear", "InvoiceMonth");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FinancasApi.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("FinancasApi.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("FinancasApi.Models.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("FinancasApi.Models.InvoicePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("InvoicePayments");
                });

            modelBuilder.Entity("FinancasApi.Models.MonthlyBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyBudgets");
                });

            modelBuilder.Entity("FinancasApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FinancasApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinancasApi.Models.Alert", b =>
                {
                    b.HasOne("FinancasApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancasApi.Models.CreditCard", b =>
                {
                    b.HasOne("FinancasApi.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancasApi.Models.Expense", b =>
                {
                    b.HasOne("FinancasApi.Models.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasApi.Models.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinancasApi.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreditCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancasApi.Models.Goal", b =>
                {
                    b.HasOne("FinancasApi.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancasApi.Models.Income", b =>
                {
                    b.HasOne("FinancasApi.Models.User", "User")
                        .WithMany("Incomes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancasApi.Models.Investment", b =>
                {
                    b.HasOne("FinancasApi.Models.User", "User")
                        .WithMany("Investments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancasApi.Models.InvoicePayment", b =>
                {
                    b.HasOne("FinancasApi.Models.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("FinancasApi.Models.MonthlyBudget", b =>
                {
                    b.HasOne("FinancasApi.Models.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancasApi.Models.RefreshToken", b =>
                {
                    b.HasOne("FinancasApi.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancasApi.Models.Category", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("FinancasApi.Models.User", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Expenses");

                    b.Navigation("Goals");

                    b.Navigation("Incomes");

                    b.Navigation("Investments");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
